theme: jekyll-theme-midnight
title: Scotty Chouan
description: Portfolio

<a href="exo2" title="Redirection vers l'exo 2" target="_blank">
<a href="exo3" title="Redirection vers l'exo 3" target="_blank">
